#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-dap1d9v40ujc73b7ai10-a.singapore-postgres.render.com/moneymanager_nitin_joshi
spring.datasource.username=moneymanager_nitin_joshi_user
spring.datasource.password=Fo3zFLZPhwlHThmJeht4jqi2DmjyjtUg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Brevo SMTP Configuration
# ===============================

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_PASSWORD}
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.smtp.from=nitinbro531@gmail.com