#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-dap1d9v40ujc73b7ai10-a.singapore-postgres.render.com/moneymanager_nitin_joshi
spring.datasource.username=moneymanager_nitin_joshi_user
spring.datasource.password=Fo3zFLZPhwlHThmJeht4jqi2DmjyjtUg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect